resources:
  - name: github
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub
 
pipelines:
  - name: pipeline
    steps:          
      - name: bash
        type: Bash
        configuration:
          inputResources:
            - name: github
        execution:
          onExecute:
            - echo "executing bash1..."
  
