resources:
  - name: github-demo
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub
#   - name: bitbucket
#     type: GitRepo
#     configuration:
#       path: bharath92/sample-runsh
#       gitProvider: bitbucket
#   - name: myCronTrigger
#     type: CronTrigger
#     configuration:
#       interval: "*/2 14 3 9 *"
 
pipelines:
  - name: pipeline-demo
    steps:          
      - name: bash-demo
        type: Bash
        configuration:
          inputResources:
            - name: github-demo
#             - name: myCronTrigger
        execution:
          onExecute:
            - echo "executing bash step..."
  
