resources:
#   - name: github
#     type: GitRepo
#     configuration:
#       path: deepikasl/VT1
#       gitProvider: deepikaGithub
  - name: myCronTrigger
    type: CronTrigger
    configuration:
      interval: "*/2 * * * *"
 
pipelines:
  - name: pipeline
    steps:          
      - name: bash
        type: Bash
        configuration:
          inputResources:
#             - name: github
            - name: myCronTrigger
        execution:
          onExecute:
            - echo "executing bash step..."
  
