resources:
  - name: sampleNodeNew
    type: gitRepo
    configuration:
      gitProvider: deepikaGithub
      path: deepikasl/VT2
 
pipelines:
  - name: pipeline1db
    steps:
      - name: stepA
        type: bash
        configuration:
          affinityGroup: build
          nodePool: myNodePool
        requires:
          resources:
            - sampleNode
        triggeredBy:
          resources:
            - utility_repo
        execution:
          onExecute:
            - echo "executing stepA..."
        #outputResources:
         # - sampleImage
       



