resources:
  - name: gitrepo_res_jTest
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        except: random
    initialVersion:
      sha: master

  - name: file_res_jTest
    type: file
    fileLocation: https://github.com/deepikasl/VT1
    fileName: shippable.yml
    configuration:
      integrationName: deepikaGithub
    initialVersion:
      fileDtTm: random_value

  - name: image_res_jTest
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: deepikaDocker
    initialVersion:
      imageTag: latest

  - name: webhookRes_jTest
    type: webhook
    configuration:
      integrationName: deepikaDocker
    initialVersion:
      payload: "asd"

  - name: clusterRes_jTest
    type: cluster
    configuration:
      integrationName: deepikaAws
      bastionHostIP: 1.2.3.4
    initialVersion:
      targetCount: 12
      targetIP01: 1.2.3.4
      targetIP02: 1.2.3.5
      targetIP03: 1.2.3.6
      targetIP04: 1.2.3.4
      targetIP05: 1.2.3.5
      targetIP06: 1.2.3.6
      targetIP07: 1.2.3.4
      targetIP08: 1.2.3.5
      targetIP09: 1.2.3.6
      targetIP10: 1.2.3.4
      targetIP11: 1.2.3.5
      targetIP12: 1.2.3.6

pipelines:
  - name: jTest_pipeline
    setup:
      runtime: onHost
    steps:
      - name: step_jTest
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - ver_1
        requires:
          integrations:
            - deepikaDocker
          resources:
            - image_res_jTest
        triggeredBy:
          resources:
            - gitrepo_res_jTest
            - image_res_jTest
            - webhookRes_jTest
            - clusterRes_jTest
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          - file_res_jTest
