resources:
  - name: sampleNode
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        only: master
     # files:
      #  only: '^\(.[a-z]*\)'
    version:
      sha: master
  - name: utility_repo
    type: gitRepo
    repoPath: deepikasl/sample-script
    configuration:
      integrationName: deepikaGithub
      branches:
        only: test
    version:
      sha: test
  - name: sampleImage
    type: image
    imageName: library/nginx
    configuration:
      integrationName: deepikaDocker
      autoPull: false
    version:
      imageTag: latest
 
pipelines:
  - name: pipeline1db
    setup:
      runtime: onHost
      environmentVariables:
        readOnly:
          ENV1_pip: value1
          ENV2_pip: value2  
    steps:
      - name: stepA
        type: bash
        configuration:
          affinityGroup: build
          nodePool: myNodePool
        #configuration:
         # nodePool: node
        setup:
          environmentVariables:
            normal:
              ENV1: value1
              ENV2: value2
        requires:
          resources:
            - sampleNode
        triggeredBy:
          resources:
            - utility_repo
        execution:
          onExecute:
            - echo "executing stepA..."
            - echo $step_triggered_by_step_name, $step_triggered_by_resource_name, $step_triggered_by_identity_name, $step_image_name, $step_image_tag, $step_runtime, $step_runtime_version, $step_platform, $step_node_id, $step_node_name, $step_node_pool_name, $step_affinity_group
            #- pushd $res_sampleNode_resourcePath
            - write_output sampleImage "imageTag="$STEP_ID
            - pushd $res_utility_repo_resourcePath
            - add_run_variable imageTag=$STEP_ID
            - save_run_state echo.sh deepika_file
            #- restore_run_state my_file test.sh
        outputResources:
          - sampleImage
       
      - name: stepB
        type: bash
        setup:
          environmentVariables:
            normal:
              ENV3: value3
              ENV4: value4
        requires:
          resources:
            - sampleNode
        triggeredBy:
          steps:
            - stepA
        execution:
          onExecute:
            - echo "executing stepB..."
            - echo "hi"


