resources:
  - name: sampleNode_cyclic
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        only: master
      files:
        only: '^\(.[a-z]*\)'
    version:
      sha: master
 
pipelines:
  - name: pipeline1db_cyclic
    setup:
      runtime: onHost
      environmentVariables:
        readOnly:
          ENV1_pip: value1
          ENV2_pip: value2  
    steps:
      - name: stepA
        type: bash
        setup:
          environmentVariables:
            normal:
              ENV1: value1
              ENV2: value2
        requires:
          resources:
            - sampleNode_cyclic
        execution:
          onExecute:
            - echo "executing stepA..."
        outputResources:
          - sampleNode_cyclic


