resources:
  - name: testRes
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: promote_go_build_publish
      buildNumber: 1
#   - name: myDockerImg_test
#     type: Image
#     configuration:
#       registry: artDocker
#       imageName: demo/app
#       imageTag: latest
#       autoPull: false
#   - name: myFile
#     type: RemoteFile
#     configuration:
#       source: dummyFileServer
#   - name: files
#     type: FileSpec
#     configuration:
#       sourceArtifactory: art
#       pattern: test-generic-local/*.zip
 
pipelines:
  - name: pipeline2db
    steps:          
      - name: testJenkins_2
        type: Jenkins
        configuration:
          integrations:
            - name: jenkins
          inputResources:
            - name: testRes
          inputSteps:
            - name: stepB

      - name: stepB
        type: Bash
        configuration:
        execution:
          onExecute:
            - echo "executing stepB..."
  
