resources:
  - name: sampleNode
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub
  - name: utility_repo
    type: GitRepo
    repoPath: deepikasl/sample-script
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
  - name: kubeClusterIntegrationResource
     type: KubeCluster
     configuration:
       kubernetesConfig: kubeInt
#        bastionHostIP: 1.2.3.4
#        bastionUser: sshUser
#        bastionIntegrationName: sshKeyIntegration
 
pipelines:
  - name: pipeline1db
    steps:
      - name: stepA
        type: Bash
        configuration:
          inputResources:
            - name: sampleNode
            - name: kubeClusterIntegrationResource
        execution:
          onExecute:
            - echo "executing stepA..."


