resources:
  - name: testRes
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: testJenkins
      buildNumber: 1
 
pipelines:
  - name: pipeline2db
    steps:          
      - name: testJenkins_2
        type: Jenkins
        configuration:
          integrations:
            - name: jenkins
          outputResources:
            - name: testRes

      - name: stepB
        type: Bash
        configuration:
          inputResources:
            - name: testRes
        execution:
          onExecute:
            - echo "executing stepB..."
  
