resources:
  - name: sampleNode
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub
  - name: utility_repo
    type: GitRepo
    repoPath: deepikasl/sample-script
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
 
pipelines:
  - name: pipeline1db
    setup:
      runtime: onHost
      environmentVariables:
        readOnly:
          ENV1_pip: value1
          ENV2_pip: value2  
    steps:
      - name: stepA
        type: Bash
        configuration:
          affinityGroup: build
          nodePool: myNodePool
          environmentVariables:
            normal:
              ENV1: value1
              ENV2: value2
          inputResources:
            - name: sampleNode
            - name: utility_repo
        execution:
          onExecute:
            - echo "executing stepA..."


