resources:
  - name: sampleNode
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        only: master
    initialVersion:
      sha: master
  - name: sample_image_test
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: dockerInt
      #autoPull: true
    initialVersion:
      imageTag: latest
  - name: sample_artifactory_image_test
    type: image
    imageName: "docker-virtual/busybox"
    configuration:
      integrationName: artifactory_int
      autoPull: true
    initialVersion:
      imageTag: latest

pipelines:
  - name: pipeline1
    setup:
      runtime: onHost
    steps:
      - name: stepA
        type: bash
        triggeredBy:
          resources:
            - sampleNode 
            - sample_image_test
            - sample_artifactory_image_test
        execution:
          onExecute:
            - echo "executing stepA..."

      - name: stepB
        type: bash
        requires:
          integrations:
            - artifactory_int
        triggeredBy:
          steps:
            - stepA 
        execution:
          onExecute:
            - echo "executing stepB..."
            - echo "apiKey is::" $int_artifactory_int_apiKey
            - echo "int url is" $int_artifactory_int_url
            - jfrog rt config default-server --url $int_artifactory_int_url --apikey $int_artifactory_int_apiKey --interactive=false
            - jfrog rt use default-server

