resources:
  - name: sampleNodeNew
    type: GitRepo
    configuration:
      gitProvider: deepikaGithub
      path: deepikasl/VT2
  
  - name: buildInfo_ap
    type: BuildInfo
    configuration:
      sourceArtifactory: deepika_artifactory
      buildName: $PIPELINE_NAME
      buildNumber: 1 # will be updated to $RUN_NUMBER after we have OUT in publish_ap step
     # targetRepo: test
 
pipelines:
  - name: pipeline1db
    steps:
#       - name: bash_ap
#         type: bash
#         configuration:
#           inputResources
#             - name: sampleNodeNew
#         execution:
#           onExecute:
#             - echo "tesfftyt"
#             - printenv

#       - name: push_ap
#         type: PushArtifactoryPackage
#         setup:
#           push:
#             targetRepo: docker-local
#         requires:
#           integrations:
#             - deepika_artifactory
#         triggeredBy:
#           steps:
#             - build_ap
            
      - name: publish_ap
        type: PublishBuildInfo
        configuration:
#           inputSteps:
#             - name: bash_ap
          outputResources:
            - name: buildInfo_ap
        #requires:
         # resources:
          #  - sampleNodeNew
        execution:
          onStart:
            - lol



