resources:
  - name: sampleNode
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub
  - name: utility_repo
    type: GitRepo
    repoPath: deepikasl/sample-script
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
 
pipelines:
  - name: pipeline1db
    steps:
      - name: stepA
        type: Bash
        configuration:
          inputResources:
            - name: sampleNode
            - name: utility_repo
        execution:
          onExecute:
            - echo "executing stepA..."


