resources:
  - name: sampleNode
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub
  - name: utility_repo
    type: GitRepo
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
#   - name: myDockerImg_test
#     type: Image
#     configuration:
#       registry: artDocker
#       imageName: demo/app
#       imageTag: latest
#       autoPull: false
#   - name: myFile
#     type: RemoteFile
#     configuration:
#       source: dummyFileServer
#   - name: files
#     type: FileSpec
#     configuration:
#       sourceArtifactory: art
#       pattern: test-generic-local/*.zip
 
pipelines:
  - name: pipeline1db
    steps:
      - name: stepAA
        type: Bash
        configuration:
          inputResources:
            - name: sampleNode
          integrations:
            - name: deepikaGithub
#           outputResources:
#             - name: myDockerImg_test
        execution:
          onExecute:
            - echo "executing stepA..."
            - if [ -z $pipeline_var ]; then add_pipeline_variables pipeline_var=1; else echo $pipeline_var; fi
#             - add_pipeline_variables pipelineId=$pipeline_id
#             - add_pipeline_variables test='test'
#             - add_run_variables test=$res_sampleNode_path
#             - add_run_variables testId=$step_id
#             - write_output myDockerImg_test "imageTag="$step_id 
#       - name: stepB
#         type: Bash
#         configuration:
#           inputResources:
#             - name: files
#           inputSteps:
#             - name: stepAA
#         execution:
#           onExecute:
#             - echo "executing stepB"
#             - if [[ $(($pipeline_var % 2)) -eq 0 ]]; then run_var+=" world"; else run_var+=" universe"; fi
#             - echo $run_var
      - name: testJenkins
        type: Jenkins
        configuration:
          integrations:
            - name: test_jenkins
          inputSteps:
            - name: stepAA
            
#       - name: stepB
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: testJenkins
#         execution:
#           onExecute:
#             - echo "executing stepB..."
  - name: pipeline2db
    steps:          
      - name: testJenkins
        type: Jenkins
        configuration:
          integrations:
            - name: test_jenkins
          inputSteps:
            - name: stepAA
      - name: stepB
        type: Bash
        configuration:
          inputSteps:
            - name: testJenkins
        execution:
          onExecute:
            - echo "executing stepB..."
