resources:
  - name: app1_deepika
    type: GitRepo
    configuration:
      gitProvider: deepikaGithub
      path: deepikasl/VT2
  
  - name: myDockerImg_test
    type: Image
    configuration:
      registry: artDocker
      imageName: demo/app
      imageTag: latest
      autoPull: false

pipelines:

  - name: test_pipeline_deepika
    steps:
      - name: build_test
        type: Bash
        configuration:
          inputResources:
            - name: app1_deepika
          outputResources:
            - name: myDockerImg_test
        execution:
          onExecute:
            - printenv
            - pushd $res_app1_deepika_resourcePath
#             - docker build -t app1_deepika:$step_id .
#             - write_output myDockerImg_test "imageTag="$step_id
#             - add_run_variables imageName=$res_myDockerImg_test_imageName
#             - add_run_variables imageTag=$step_id
         


      - name: test_deepika
        type: Bash
        configuration:
          inputResources:
            - name: myDockerImg_test
        execution:
          onExecute:
            - printenv
