resources:
  - name: sampleNode
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        only: master
      files:
        only: '^\(.[a-z]*\)'
    initialVersion:
      sha: master
  - name: sampleImage
    type: image
    imageName: library/nginx
    configuration:
      integrationName: deepikaDocker
      autoPull: false
    initialVersion:
      imageTag: latest
 
pipelines:
  - name: pipeline1db
    setup:
      runtime: onHost
    steps:
      - name: stepA
        type: bash
        #configuration:
         # nodePool: node
        setup:
          environmentVariables:
            normal:
              ENV1: value1
              ENV2: value2
        requires:
          resources:
            - sampleNode
        execution:
          onExecute:
            - echo "executing stepA..."
            - pushd $res_app1_resourcePath
            - docker build -t app1:$STEP_ID .
            - write_output myDockerImg "imageTag="$STEP_ID
        outputResources:
          - sampleImage
       
      - name: stepB
        type: bash
        setup:
          environmentVariables:
            normal:
              ENV3: value3
              ENV4: value4
        triggeredBy:
          resources:
            - sampleNode
          steps:
            - stepA
        execution:
          onExecute:
            - echo "executing stepB..."


