resources:
  - name: sampleNode_new
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        only: master
      files:
        only: '^\(.[a-z]*\)'
    initialVersion:
      sha: master
 
pipelines:
  - name: pipeline1db
    setup:
      runtime: onHost
    steps:
      - name: stepAA
        type: bash
        triggeredBy:
          resources:
            - sampleNode_new
        execution:
          onExecute:
            - echo "executing stepA..."
       
      - name: stepBB
        type: bash
        triggeredBy:
          resources:
            - sampleNode_new
        execution:
          onExecute:
            - echo "executing stepB..."


