resources:
  - name: sampleNode
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub
  - name: utility_repo
    type: gitRepo
    repoPath: deepikasl/sample-script
    configuration:
      integrationName: deepikaGithub
      branches:
        only: test
    version:
      sha: test
  - name: sampleImage
    type: image
    imageName: library/nginx
    configuration:
      integrationName: deepikaDocker
      autoPull: false
    version:
      imageTag: latest
 
pipelines:
  - name: pipeline1db
    setup:
      runtime: onHost
      environmentVariables:
        readOnly:
          ENV1_pip: value1
          ENV2_pip: value2  
    steps:
      - name: stepA
        type: Bash
        configuration:
          affinityGroup: build
          nodePool: myNodePool
          environmentVariables:
            normal:
              ENV1: value1
              ENV2: value2
          inputResources:
            - name: sampleNode
            - name: utility_repo
        execution:
          onExecute:
            - echo "executing stepA..."
            - pushd $res_utility_repo_resourcePath
            - add_run_variable imageTag=$STEP_ID
            - save_run_state echo.sh deepika_file
            #- restore_run_state my_file test.sh
        outputResources:
          - sampleImage
       
      - name: stepB
        type: Bash
        configuration:
          environmentVariables:
            normal:
              ENV3: value3
              ENV4: value4
          inputResources:
            - name: sampleNode
          inputSteps:
            - name: stepA
        execution:
          onExecute:
            - echo "executing stepB..."
            - echo "hi"


