resources:
  - name: sampleNodeNew
    type: GitRepo
    configuration:
      gitProvider: deepikaGithub
      path: deepikasl/VT2
  
  - name: buildInfo_ap
    type: BuildInfo
    configuration:
      buildName: $PIPELINE_NAME
      buildNumber: 1 # will be updated to $RUN_NUMBER after we have OUT in publish_ap step
     # targetRepo: test
 
pipelines:
  - name: pipeline1db
    steps:
      - name: bash_ap
        type: bash
        execution:
          onExecute:
            - echo "tesfftyt"
            - printenv

#       - name: push_ap
#         type: PushArtifactoryPackage
#         setup:
#           push:
#             targetRepo: docker-local
#         requires:
#           integrations:
#             - deepika_artifactory
#         triggeredBy:
#           steps:
#             - build_ap
            
      - name: publish_ap
        type: publish
        configuration:
          inputSteps:
            - name: bash_ap
          outputResources:
            - name: buildInfo_ap
        requires:
          resources:
            - sampleNodeNew



