resources:
  - name: sampleNodeNew
    type: GitRepo
    configuration:
      gitProvider: deepikaGithub
      path: deepikasl/VT2
  
  - name: buildInfo_ap
    type: BuildInfo
    configuration:
      sourceArtifactory: deepika_artifactory
      buildName: $PIPELINE_NAME
      buildNumber: 1 # will be updated to $RUN_NUMBER after we have OUT in publish_ap step
     # targetRepo: test
 
pipelines:
  - name: pipeline1db
    steps:
      - name: mvn_build
        type: MvnBuild
        configuration:
          sourceLocation: test
          mvnCommand: test
          configFileLocation: test
          configFileName: test
          integrations:
            - name: deepika_artifactory
          inputResources:
            - name: sampleNodeNew
        execution:
          onExecute:
            - echo "tesfftyt"
            - printenv

      - name: push_ap
        type: PushArtifactoryPackage
        configuration:
          targetRepo: lalal
          integrations:
            - name: deepika_artifactory
          inputSteps: 
            - name: mvn_build
#         setup:
#           push:
#             targetRepo: docker-local
#         requires:
#           integrations:
#             - deepika_artifactory
#         triggeredBy:
#           steps:
#             - build_ap
            
      - name: publish_ap
        type: PublishBuildInfo
        configuration:
          integrations:
            - name: deepika_artifactory
          inputSteps:
            - name: push_ap
          outputResources:
            - name: buildInfo_ap
        #requires:
         # resources:
          #  - sampleNodeNew
        execution:
          onStart:
            - lol



