      
pipelines:
  - name: deepika_pipeline
    steps:
      - name: step_1
        type: Bash
        execution:
          onExecute:
            - echo "hi"
      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "hi1"
            
