resources:
  - name: sampleNode_new
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        only: master
      files:
        only: '^\(.[a-z]*\)'
    version:
      sha: master
  - name: utility_repo1
    type: gitRepo
    repoPath: deepikasl/sample-script
    configuration:
      integrationName: deepikaGithub
      branches:
        only: test
    version:
      sha: test
 
pipelines:
  - name: pipeline2db
    setup:
      runtime: onHost
    steps:
      - name: stepAA
        type: bash
        requires:
          resources:
            - sampleNode_new
        execution:
          onExecute:
            - echo "executing stepA..."
       
      - name: stepBB
        type: bash
        requires:
          resources:
            - sampleNode_new
        execution:
          onExecute:
            - echo "executing stepB..."


