resources:
  - name: sampleNode
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        only: master
    initialVersion:
      sha: master
  - name: sample_image_test
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: dockerInt
      #autoPull: true
    initialVersion:
      imageTag: latest
  - name: sample_artifactory_image_test
    type: image
    imageName: "docker-virtual/busybox"
    configuration:
      integrationName: artifactory_int
      autoPull: true
    initialVersion:
      imageTag: latest
  - name: sample_cluster_ssh_test
    type: cluster
    configuration:
      integrationName: deepikaSSH
    initialVersion:
      targetCount: 3
      targetIP05: 1.2.3.4
      targetIP02: 1.2.3.5
      targetIP03: 1.2.3.6


pipelines:
  - name: pipeline1
    setup:
      runtime: onHost
    steps:
      - name: stepA
        type: bash
        requires:
          resources:
            - sampleNode 
            - sample_cluster_ssh_test
        execution:
          onExecute:
            - echo "executing stepA..."

      - name: stepB
        type: bash
        requires:
          integrations:
            - artifactory_int
        triggeredBy:
          steps:
            - stepA 
        execution:
          onExecute:
            - echo "executing stepB..."

