resources:
  - name: sampleNode_native
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        only: master
      files:
        only: '^\(.[a-z]*\)'
    version:
      sha: master
  - name: file_ap
    type: file
    configuration:
      integrationName: deepika_artifactory
    version:
      pattern: "example-repo-local/"

  - name: buildInfo_ap
    type: buildInfo
    version:
      buildName: $PIPELINE_NAME
      buildNumber: 1 # will be updated to $RUN_NUMBER after we have OUT in publish_ap step
     # targetRepo: test
      
  - name: promoteInfo_ap
    type: buildInfo
    version:
      buildName: promote_bldinfo
      buildNumber: 1  
 
pipelines:
  - name: deepika_pipeline_native
    steps:  
      - name: bash_ap
        type: bash
        execution:
          onExecute:
            - echo "tesfftyt"
            - printenv

      - name: build_ap
        type: build
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: 34.66.110.173:8081/docker-local/ankul
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        triggeredBy:
          resources:
            - sampleScript_ap
          steps:
            - bash_ap
        requires:
          integrations:
            - deepika_artifactory
          resources:
            - file_ap

      - name: push_ap
        type: push
        setup:
          push:
            targetRepo: docker-local
        requires:
          integrations:
            - deepika_artifactory
        triggeredBy:
          steps:
            - build_ap
            
      - name: publish_ap
        type: publish
        requires:
          integrations:
            - deepika_artifactory
        triggeredBy:
          steps:
            - push_ap
        outputResources:
          - buildInfo_ap
      
      - name: promote_ap
        type: promote
        setup:
          promote:
            targetRepo: varsha_local_repo    
        requires:
          integrations:
            - deepika_artifactory         
        triggeredBy:
          resources:
            - buildInfo_ap
        outputResources:
          - promoteInfo_ap 
