pipelines:
  - name: pipeline2db
    steps:
      - name: stepB
        type: Bash
        configuration:
          inputResources:
            - name: myDockerImg_test
        execution:
          onExecute:
            - echo "executing stepB"
