resources:
  - name: sampleNode
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        only: master
      files:
        only: '^\(.[a-z]*\)'
    initialVersion:
      sha: master
  - name: utility_repo
    type: gitRepo
    repoPath: deepikasl/sample-script
    configuration:
      integrationName: deepikaGithub
      branches:
        only: test
    initialVersion:
      sha: test
  - name: sampleImage
    type: image
    imageName: library/nginx
    configuration:
      integrationName: deepikaDocker
      autoPull: false
    initialVersion:
      imageTag: latest
 
pipelines:
  - name: pipeline1db
    setup:
      runtime: onHost
    steps:
      - name: stepA
        type: bash
        #configuration:
         # nodePool: node
        setup:
          environmentVariables:
            normal:
              ENV1: value1
              ENV2: value2
        requires:
          resources:
            - sampleNode
        execution:
          onExecute:
            - echo "executing stepA..."
            - pushd $res_sampleNode_resourcePath
            - write_output sampleImage "imageTag="$STEP_ID
            - pushd $res_utility_repo_resourcePath
            - add_run_variable imageTag=$STEP_ID
            - save_run_state test.sh deepika_file
            #- restore_run_state my_file test.sh
        outputResources:
          - sampleImage
       
      - name: stepB
        type: bash
        setup:
          environmentVariables:
            normal:
              ENV3: value3
              ENV4: value4
        requires:
          resources:
            - sampleNode
        triggeredBy:
          steps:
            - stepA
        execution:
          onExecute:
            - echo "executing stepB..."


