resources:
  - name: sampleNode
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        only: master
    initialVersion:
      sha: master
  - name: sample_image_test
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: dockerInt
      #autoPull: true
    initialVersion:
      imageTag: latest
  - name: sample_artifactory_image_test
    type: image
    imageName: "docker-virtual/busybox"
    configuration:
      integrationName: artifactory_int
      autoPull: true
    initialVersion:
      imageTag: latest
  - name: sample_gcloud_test
    type: file
    fileLocation: https://console.cloud.google.com/storage/browser/testdeepika/identityRoles-deleteById-flowChart.xml
    configuration:
      integrationName: deepikaGoogleCloud
      autoPull: true
    initialVersion:
      fileName: 'identityRoles-deleteById-flowChart'

pipelines:
  - name: pipeline1
    setup:
      runtime: onHost
    steps:
      - name: stepA
        type: bash
        requires:
          resources:
            - sampleNode 
            - sample_gcloud_test
        execution:
          onExecute:
            - echo "executing stepA..."

      - name: stepB
        type: bash
        requires:
          integrations:
            - deepikaGoogleCloud
        triggeredBy:
          steps:
            - stepA 
        execution:
          onExecute:
            - echo "executing stepB..."
            - echo $int_deepikaGoogleCloud_jsonKey
            - projectId="$( echo "$int_deepikaGoogleCloud_jsonKey" | jq -r '.project_id' )"
            - touch key.json
            - echo "$jsonKey" > key.json
            - gcloud -q auth activate-service-account --key-file "key.json"
            - gcloud config set project "$projectId"
            - fileLocation='https://console.cloud.google.com/storage/browser/testdeepika/identityRoles-deleteById-flowChart.xml'
            - gcloud compute scp --recurse $fileLocation $resourcePath

