resources:
  - name: sampleNode
    type: gitRepo
    repoPath: deepikasl/VT2
    configuration:
      integrationName: deepikaGithub
      branches:
        only: master
    initialVersion:
      sha: master
  - name: sample_image_test
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: dockerInt
      #autoPull: true
    initialVersion:
      imageTag: latest

pipelines:
  - name: pipeline1
    setup:
      runtime: onHost
    steps:
      - name: stepA
        type: bash
        triggeredBy:
          resources:
            - sampleNode 
            - sample_image_test
        execution:
          onExecute:
            - echo "executing stepA..."

      - name: stepB
        type: bash
        triggeredBy:
          steps:
            - stepA 
        execution:
          onExecute:
            - echo "executing stepB..."
